# Generated by Django 5.1.6 on 2025-02-21 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name': 'Movimentação de Bem', 'verbose_name_plural': 'Movimentações de Bens'},
        ),
        migrations.RenameField(
            model_name='movimentacao',
            old_name='data_movimentacao',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Movimentação'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_destino', to='departamentos.departamento', verbose_name='Departamento de Destino'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_origem', to='departamentos.departamento', verbose_name='Departamento de Origem'),
        ),
    ]
