# Generated by Django 5.1.6 on 2025-02-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Bem')),
                ('identificador_rfid', models.CharField(max_length=50, unique=True, verbose_name='Etiqueta RFID')),
                ('data_aquisicao', models.DateField(verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('baixado', 'Baixado'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=50)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.departamento', verbose_name='Departamento Atual')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor', verbose_name='Fornecedor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonio.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Bem Patrimonial',
                'verbose_name_plural': 'Bens Patrimoniais',
            },
        ),
    ]
